import sys; sys.path.append("../.."); from practice_engine import Task, Level, run_task
def verify_easy(g): return 'sum_all' in g and callable(g['sum_all']) and 's' in g and g['s']==10
easy=Task("Define `sum_all(*args)` returning sum of args, call with 1,2,3,4 into 's'", verify_easy, Level.EASY, hints=["def sum_all(*args): return sum(args)","s=sum_all(1,2,3,4)"])
def verify_medium(g): return 'print_info' in g and callable(g['print_info']) and 'info' in g and isinstance(g['info'],str) and 'Emperor' in g['info']
medium=Task("Define `print_info(**kwargs)` that returns a string like 'name: Emperor, age: 18' (format nicely). Call with name='Emperor', age=18 into 'info'.", verify_medium, Level.MEDIUM, hints=["def print_info(**kwargs):\n    parts=[]\n    for k,v in kwargs.items():\n        parts.append(f'{k}: {v}')\n    return ', '.join(parts)","info=print_info(name='Emperor', age=18)"])
def verify_hard(g): return 'combined' in g and callable(g['combined']) and 'c1' in g and g['c1']==6 and 'c2' in g and isinstance(g['c2'],str) and 'x=5' in g['c2']
hard=Task("Define `combined(a,b,*args,**kwargs)` returning a+b if no kwargs, else a string with kwargs. Call with 1,2 into 'c1' (should be 3? Actually a+b=3 but we said 6? let's adjust: combined should sum a and all args? We'll design: combined(a,b,*args) returns a+b+sum(args). We'll check that. Let's make simple: define function that returns a+b+sum(args). So c1=combined(1,2) => 3. But our expected c1=6? That's confusing. Let's design: combined(1,2,3) => 6. So a,b,*args. a=1,b=2,args=(3,). sum a+b+sum(args)=6. So c1=combined(1,2,3) returns 6. c2 with kwargs: we'll return string. So task: call combined(1,2,3) into 'c1' to get 6, and combined(x=5,y=6) should return something like 'x=5, y=6' into 'c2'. But we need to differentiate: the function signature will be combined(a,b,*args,**kwargs). So to get c1 we pass three numbers: combined(1,2,3) => a=1,b=2,*args=(3,) => sum 1+2+3=6. To get c2 we call combined(0,0,x=5,y=6). That's messy. I'll simplify: use separate tasks? But we need one hard task. I'll design: `def mixed(*args, **kwargs): return sum(args) if not kwargs else str(kwargs)`. Then call mixed(1,2,3) => 6 into 'c1', mixed(name='Emperor') => dictionary string? But verification can check c1 == 6 and 'name' in c2. Let's implement that. So define mixed to handle both. We'll instruct: "Define function `mixed(*args, **kwargs)` that returns sum(args) if kwargs is empty, else returns str(kwargs). Call mixed(1,2,3) into 'c1', and mixed(name='Emperor') into 'c2'." Then verify c1 == 6 and "name" in c2. Good.", verify_hard, Level.HARD, hints=["def mixed(*args, **kwargs):\n    if not kwargs:\n        return sum(args)\n    else:\n        return str(kwargs)","c1=mixed(1,2,3)","c2=mixed(name='Emperor')"])
def main(): c=input("1 Easy 2 Med 3 Hard "); tasks={"1":easy,"2":medium,"3":hard}; run_task(tasks.get(c,easy))
if __name__=="__main__": main()
